function bp_param = New_BandpassParameters(r, chan_str)
%all default parameters come from DefaultParameters function
bp_param = DefaultParameters('New Band Pass');
bp_param.ChannelStr = chan_str;
%ask to edit parameters
prompt = { ...
    'New Label:', ...
    'Frame Left [s]:', ...
    'Frame Right [s]:', ...
    'Min Frequency [Hz]:', ...
    'Max Frequency [Hz]:', ...
    'Filter Order:', ...
    'Channel:'};
name = 'Bandpass Parameters';
numlines = 1;
defaultanswer = {...
    sprintf('%s via Event Group #%d', bp_param.Label,r.ReferencePointer), ...
    sprintf('%.3f', bp_param.LeftFrame), ...
    sprintf('%.3f', bp_param.RightFrame), ...
    sprintf('%.3f', bp_param.MinFrequency), ...
    sprintf('%.3f', bp_param.MaxFrequency), ...
    sprintf('%d', bp_param.FilterOrder), ...
    sprintf('%s', bp_param.ChannelStr)};
answer=inputdlg(prompt,name,numlines,defaultanswer);
%user canceled
if isempty(answer)
    %to let parent function to know that user canceled
    bp_param = [];
    return
end

%convert inputs from strings to whatever:
bp_param.Label = answer{1};
bp_param.LeftFrame = str2double(answer{2});
bp_param.RightFrame = str2double(answer{3});
bp_param.MinFrequency = str2double(answer{4});
bp_param.MaxFrequency = str2double(answer{5});
bp_param.FilterOrder = str2double(answer{6});
bp_param.ChannelStr = answer{7};